

[[benchmarks]]
name = "article-test-a"
datasets = ["mother"]
tools = ["cuttlefish2-reads", "ggcat"]
working-dirs = ["hdd"]
copy-dataset = false
kvalues = [27, 63]
threads = [12]
min-multiplicity = 2
size-check-time = 2000
copy-output = true


[[benchmarks]]
name = "article-test-b"
datasets = ["salmonella-all"]
tools = ["cuttlefish2-ref", "ggcat"]
working-dirs = ["hdd"]
copy-dataset = true
kvalues = [27, 63, 119, 255]
threads = [12]
min-multiplicity = 1
size-check-time = 2000
copy-output = false

[[benchmarks]]
name = "article-test-c"
datasets = ["gut"]
tools = ["cuttlefish2-reads", "ggcat"]
working-dirs = ["ssd"]
copy-dataset = true
kvalues = [27, 63, 119, 255]
threads = [12]
min-multiplicity = 2
size-check-time = 2000
copy-output = true

[[benchmarks]]
name = "article-test-d-k27"
datasets = ["human-100"]
tools = ["ggcat-colored", "bifrost-colored"]
working-dirs = ["ssd"]
copy-dataset = false
kvalues = [27]
threads = [16]
min-multiplicity = 1
size-check-time = 2000
copy-output = true

[[benchmarks]]
name = "article-test-d-k63"
datasets = ["human-100"]
tools = ["ggcat-colored", "bifrost-colored-k63"]
working-dirs = ["ssd"]
copy-dataset = false
kvalues = [63]
threads = [16]
min-multiplicity = 1
size-check-time = 2000
copy-output = true

[[benchmarks]]
name = "article-test-e-k27"
datasets = ["salmonella-100k"]
tools = ["ggcat-colored", "bifrost-colored"]
working-dirs = ["ssd"]
copy-dataset = true
kvalues = [27]
threads = [16]
min-multiplicity = 1
size-check-time = 2000
copy-output = true

[[benchmarks]]
name = "article-test-e-k63"
datasets = ["salmonella-100k"]
tools = ["ggcat-colored", "bifrost-colored"]
working-dirs = ["ssd"]
copy-dataset = true
kvalues = [63]
threads = [16]
min-multiplicity = 1
size-check-time = 2000
copy-output = true

[[benchmarks]]
name = "article-test-f"
datasets = ["salmonella-10", "salmonella-100", "salmonella-1k", "salmonella-5k", "salmonella-10k", "salmonella-50k", "salmonella-100k"]
tools = ["cuttlefish2-ref", "ggcat"]
working-dirs = ["ssd"]
copy-dataset = true
kvalues = [63]
threads = [16]
min-multiplicity = 1
size-check-time = 2000
copy-output = false

[[benchmarks]]
name = "article-test-g"
datasets = ["human-50-nvme"]
tools = ["ggcat"]
working-dirs = ["nvme"]
copy-dataset = false
kvalues = [63]
threads = [16]
min-multiplicity = 1
size-check-time = 2000
copy-output = false


[[benchmarks]]
name = "salmonella-small"
datasets = ["salmonella-10", "salmonella-100", "salmonella-1k"]
tools = ["cuttlefish2-ref", "ggcat", "bcalm"]
working-dirs = ["ssd"]
copy-dataset = true
kvalues = [27, 63, 119, 255]
threads = [16]
min-multiplicity = 1
size-check-time = 500

[[benchmarks]]
name = "salmonella-big"
datasets = ["salmonella-5k", "salmonella-10k", "salmonella-50k", "salmonella-100k"]
tools = ["cuttlefish2-ref", "ggcat"]
working-dirs = ["ssd"]
copy-dataset = true
kvalues = [27, 63, 119, 255]
threads = [16]
min-multiplicity = 1
size-check-time = 500
copy-output = false

[[benchmarks]]
name = "salmonella-huge"
datasets = ["salmonella-all"]
tools = ["cuttlefish2-ref", "ggcat"]
working-dirs = ["ssd"]
copy-dataset = true
kvalues = [27, 63, 119, 255]
threads = [16]
min-multiplicity = 1
size-check-time = 2000
copy-output = false


[[benchmarks]]
name = "colored-salmonella-small"
datasets = ["salmonella-10", "salmonella-100", "salmonella-1k"]
tools = ["bifrost-colored", "ggcat-colored"]
working-dirs = ["ssd"]
copy-dataset = true
kvalues = [27]
threads = [16]
min-multiplicity = 1
size-check-time = 500

[[benchmarks]]
name = "colored-salmonella-big"
datasets = ["salmonella-5k", "salmonella-10k", "salmonella-50k", "salmonella-100k"]
tools = ["bifrost-colored", "ggcat-colored"]
working-dirs = ["ssd"]
copy-dataset = true
kvalues = [27]
threads = [16]
min-multiplicity = 1
size-check-time = 2000
copy-output = false

[[benchmarks]]
name = "colored-salmonella-huge"
datasets = ["salmonella-all"]
tools = ["bifrost-colored", "ggcat-colored"]
working-dirs = ["ssd"]
copy-dataset = true
kvalues = [27]
threads = [16]
min-multiplicity = 1
size-check-time = 2000
copy-output = false


[[benchmarks]]
name = "gut-complete"
datasets = ["gut"]
tools = ["cuttlefish2-reads", "ggcat"]
working-dirs = ["ssd"]
copy-dataset = true
kvalues = [27, 63, 119, 255]
threads = [16]
min-multiplicity = 2
size-check-time = 1000
copy-output = false

[[benchmarks]]
name = "human"
datasets = ["father", "mother"]
tools = ["cuttlefish2-reads", "ggcat"]
working-dirs = ["ssd"]
copy-dataset = false
kvalues = [27, 63, 119, 255]
threads = [16]
min-multiplicity = 2
size-check-time = 1000
copy-output = false


[[benchmarks]]
name = "human-colored-k27"
datasets = ["human-5", "human-10", "human-50", "human-100"]
tools = ["ggcat-colored", "bifrost-colored"]
working-dirs = ["ssd"]
copy-dataset = false
kvalues = [27]
threads = [16]
min-multiplicity = 1
size-check-time = 1000
copy-output = true

[[benchmarks]]
name = "human-colored-k63"
datasets = ["human-5", "human-10", "human-50", "human-100"]
tools = ["ggcat-colored", "bifrost-colored-k63"]
working-dirs = ["ssd"]
copy-dataset = false
kvalues = [63]
threads = [16]
min-multiplicity = 1
size-check-time = 1000
copy-output = true


[[benchmarks]]
name = "human-colored-query-1-ggcat"
datasets = ["human-100-cq1-ggcat-colored-query"]
tools = ["ggcat-query-colored"]
working-dirs = ["ssd"]
copy-dataset = false
kvalues = [63]
threads = [16]
min-multiplicity = 1
size-check-time = 1000
copy-output = true

[[benchmarks]]
name = "human-colored-query-1-bifrost"
datasets = ["human-100-cq1-bifrost-colored-k63-query"]
tools = ["bifrost-colored-k63-query"]
working-dirs = ["ssd"]
copy-dataset = false
kvalues = [63]
threads = [16]
min-multiplicity = 1
size-check-time = 1000
copy-output = true

[[benchmarks]]
name = "human-query-1-ggcat"
datasets = ["human-100-q1-ggcat-query"]
tools = ["ggcat-query"]
working-dirs = ["ssd"]
copy-dataset = false
kvalues = [63]
threads = [16]
min-multiplicity = 1
size-check-time = 1000
copy-output = true

[[benchmarks]]
name = "human-query-1-bifrost"
datasets = ["human-100-q1-bifrost-k63-query"]
tools = ["bifrost-k63-query"]
working-dirs = ["ssd"]
copy-dataset = false
kvalues = [63]
threads = [16]
min-multiplicity = 1
size-check-time = 1000
copy-output = true
