
[[benchmarks]]
name = "salmonella-small"
datasets = ["salmonella-10", "salmonella-100", "salmonella-1k"]
tools = ["cuttlefish2-ref", "ggcat"]
working-dirs = ["ssd"]
copy-dataset = true
kvalues = [27, 63]
threads = [16]
min-multiplicity = 1
size-check-time = 500

[[benchmarks]]
name = "salmonella-big"
datasets = ["salmonella-5k", "salmonella-10k", "salmonella-50k", "salmonella-100k"]
tools = ["cuttlefish2-ref", "ggcat"]
working-dirs = ["ssd"]
copy-dataset = true
kvalues = [27, 63]
threads = [16]
min-multiplicity = 1
size-check-time = 500
copy-output = false

[[benchmarks]]
name = "salmonella-huge"
datasets = ["salmonella-all"]
tools = ["cuttlefish2-ref", "ggcat"]
working-dirs = ["ssd"]
copy-dataset = true
kvalues = [27, 63]
threads = [16]
min-multiplicity = 1
size-check-time = 2000
copy-output = false


[[benchmarks]]
name = "colored-salmonella-small"
datasets = ["salmonella-10", "salmonella-100", "salmonella-1k"]
tools = ["bifrost-colored", "ggcat-colored"]
working-dirs = ["ssd"]
copy-dataset = true
kvalues = [27]
threads = [16]
min-multiplicity = 1
size-check-time = 500

[[benchmarks]]
name = "colored-salmonella-big"
datasets = ["salmonella-5k", "salmonella-10k", "salmonella-50k", "salmonella-100k"]
tools = ["bifrost-colored", "ggcat-colored"]
working-dirs = ["ssd"]
copy-dataset = true
kvalues = [27]
threads = [16]
min-multiplicity = 1
size-check-time = 2000
copy-output = false

[[benchmarks]]
name = "colored-salmonella-huge"
datasets = ["salmonella-all"]
tools = ["bifrost-colored", "ggcat-colored"]
working-dirs = ["ssd"]
copy-dataset = true
kvalues = [27]
threads = [16]
min-multiplicity = 1
size-check-time = 2000
copy-output = false


[[benchmarks]]
name = "gut-complete"
datasets = ["gut"]
tools = ["cuttlefish2-reads", "ggcat"]
working-dirs = ["ssd"]
copy-dataset = true
kvalues = [27, 63]
threads = [16]
min-multiplicity = 2
size-check-time = 1000
copy-output = false

[[benchmarks]]
name = "human"
datasets = ["father", "mother"]
tools = ["cuttlefish2-reads", "ggcat"]
working-dirs = ["ssd"]
copy-dataset = false
kvalues = [27, 63]
threads = [16]
min-multiplicity = 2
size-check-time = 1000
copy-output = false
