[[tools]]
name = "bifrost"
path = "../tools/Bifrost"
arguments = "build -k <KVALUE> -t <THREADS>  <INPUT_FILES_LIST> -o <OUTPUT_FILE> --verbose"
reads-arg-prefix = "-r"
sequences-arg-prefix = "-s"
use-prefix-for-list = true

[[tools]]
name = "bifrost-k63"
path = "../tools/Bifrost-k63"
arguments = "build -k <KVALUE> -t <THREADS>  <INPUT_FILES_LIST> -o <OUTPUT_FILE> --verbose"
reads-arg-prefix = "-r"
sequences-arg-prefix = "-s"
use-prefix-for-list = true


[[tools]]
name = "bifrost-colored"
path = "../tools/Bifrost"
arguments = "build -k <KVALUE> -t <THREADS>  <INPUT_FILES_LIST> -o <OUTPUT_FILE> --verbose -c"
reads-arg-prefix = "-r"
sequences-arg-prefix = "-s"
use-prefix-for-list = true

[[tools]]
name = "bifrost-colored-k63"
path = "../tools/Bifrost-k63"
arguments = "build -k <KVALUE> -t <THREADS>  <INPUT_FILES_LIST> -o <OUTPUT_FILE> --verbose -c"
reads-arg-prefix = "-r"
sequences-arg-prefix = "-s"
use-prefix-for-list = true

[[tools]]
name = "bifrost-colored-k63-query"
path = "../tools/Bifrost-k63"
arguments = "build -k <KVALUE> -t <THREADS> -g <INPUT_GRAPH> -q <INPUT_QUERY>  -o <OUTPUT_FILE> --verbose"
reads-arg-prefix = "-r"
sequences-arg-prefix = "-s"
use-prefix-for-list = true

[[tools]]
name = "bifrost-colored-k63-query-colored"
path = "../tools/Bifrost-k63"
arguments = "build -k <KVALUE> -t <THREADS> -g <INPUT_GRAPH> -q <INPUT_QUERY>  -o <OUTPUT_FILE> --verbose -c"
reads-arg-prefix = "-r"
sequences-arg-prefix = "-s"
use-prefix-for-list = true


[[tools]]
name = "cuttlefish2-ref"
path = "../tools/cuttlefish"
arguments = "build --ref -l <INPUT_FILES_LIST> -k <KVALUE> -c <MULTIPLICITY> -t <THREADS> -o <OUTPUT_FILE>  -w <TEMP_DIR>"

[[tools]]
name = "cuttlefish2-reads"
path = "../tools/cuttlefish"
arguments = "build --read -l <INPUT_FILES_LIST> -k <KVALUE> -c <MULTIPLICITY> -t <THREADS> -o <OUTPUT_FILE>  -w <TEMP_DIR>"


[[tools]]
name = "bcalm"
path = "../tools/bcalm"
arguments = "-in <INPUT_FILES_LIST> -kmer-size <KVALUE> -nb-cores <THREADS> -abundance-min <MULTIPLICITY> -out-tmp <TEMP_DIR> -out <OUTPUT_FILE>"

[[tools]]
name = "ggcat"
path = "../tools/ggcat"
arguments = "build -k <KVALUE> -j <THREADS> -s <MULTIPLICITY> -l <INPUT_FILES_LIST> -t <TEMP_DIR> -o <OUTPUT_FILE>"

[[tools]]
name = "ggcat-colored"
path = "../tools/ggcat"
arguments = "build -k <KVALUE> -j <THREADS> -s <MULTIPLICITY> -l <INPUT_FILES_LIST> -t <TEMP_DIR> -o <OUTPUT_FILE> --colors"

[[tools]]
name = "ggcat-query"
path = "../tools/ggcat"
arguments = "query -k <KVALUE> -j <THREADS> <INPUT_GRAPH> <INPUT_QUERY> -t <TEMP_DIR> -o <OUTPUT_FILE>"

[[tools]]
name = "ggcat-query-colored"
path = "../tools/ggcat"
arguments = "query -k <KVALUE> -j <THREADS> <INPUT_GRAPH> <INPUT_QUERY> -t <TEMP_DIR> -o <OUTPUT_FILE> --colors"

[[tools]]
name = "ggcat-ram"
path = "../tools/ggcat"
arguments = "build -k <KVALUE> -j <THREADS> -s <MULTIPLICITY> -l <INPUT_FILES_LIST> -t <TEMP_DIR> -o <OUTPUT_FILE> --prefer-memory"

